import { useState, useRef, type KeyboardEvent } from 'react';
import { Send, Sparkles } from 'lucide-react';
import { cn } from '../ui';

interface ChatbotInputProps {
  onSend: (message: string) => void;
  disabled?: boolean;
  placeholder?: string;
}

export function ChatbotInput({ onSend, disabled, placeholder }: ChatbotInputProps) {
  const [input, setInput] = useState('');
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  const handleSend = () => {
    const trimmed = input.trim();
    if (!trimmed || disabled) return;
    onSend(trimmed);
    setInput('');
    if (textareaRef.current) {
      textareaRef.current.style.height = 'auto';
    }
  };

  const handleKeyDown = (e: KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  const handleInput = () => {
    if (textareaRef.current) {
      textareaRef.current.style.height = 'auto';
      textareaRef.current.style.height = `${Math.min(textareaRef.current.scrollHeight, 120)}px`;
    }
  };

  return (
    <div className="border-t border-obsidian-100 dark:border-obsidian-700 bg-white dark:bg-obsidian-900 p-3">
      <div className="flex items-end gap-2">
        <div className="flex-1 relative">
          <textarea
            ref={textareaRef}
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={handleKeyDown}
            onInput={handleInput}
            placeholder={placeholder || 'Ask me anything about SomaHub...'}
            rows={1}
            disabled={disabled}
            className={cn(
              'w-full resize-none rounded-xl border bg-obsidian-50 dark:bg-obsidian-800 px-4 py-2.5 pr-10 text-sm',
              'border-obsidian-200 dark:border-obsidian-600',
              'placeholder-obsidian-400 dark:placeholder-obsidian-500',
              'focus:outline-none focus:ring-2 focus:ring-emerald-400 focus:border-emerald-400',
              'transition-all duration-150',
              disabled && 'opacity-50 cursor-not-allowed',
            )}
          />
          <Sparkles
            size={14}
            className="absolute right-3 bottom-3 text-emerald-400 opacity-50"
          />
        </div>
        <button
          type="button"
          onClick={handleSend}
          disabled={!input.trim() || disabled}
          className={cn(
            'flex-shrink-0 w-10 h-10 rounded-xl flex items-center justify-center transition-all duration-150',
            input.trim() && !disabled
              ? 'bg-emerald-600 text-white hover:bg-emerald-700 shadow-sm'
              : 'bg-obsidian-100 dark:bg-obsidian-700 text-obsidian-400 cursor-not-allowed',
          )}
        >
          <Send size={16} />
        </button>
      </div>
      <p className="text-[10px] text-obsidian-400 dark:text-obsidian-500 text-center mt-1.5">
        Responses are generated by AI and may not be accurate. Press Enter to send.
      </p>
    </div>
  );
}
