"""initial_schema

Revision ID: 1598662b6661
Revises:
Create Date: 2026-06-23 10:15:43.400780

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1598662b6661"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenants",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("library_type", sa.String(length=100), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("plan", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(op.f("ix_tenants_slug"), "tenants", ["slug"], unique=True)
    op.create_table(
        "books",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("isbn", sa.String(length=32), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("author", sa.String(length=255), nullable=False),
        sa.Column("publisher", sa.String(length=255), nullable=True),
        sa.Column("publication_year", sa.Integer(), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("cover_url", sa.Text(), nullable=True),
        sa.Column("total_copies", sa.Integer(), nullable=False),
        sa.Column("available_copies", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "isbn", name="uq_books_tenant_isbn"),
    )
    op.create_index(op.f("ix_books_author"), "books", ["author"], unique=False)
    op.create_index(op.f("ix_books_category"), "books", ["category"], unique=False)
    op.create_index(
        "ix_books_tenant_author", "books", ["tenant_id", "author"], unique=False
    )
    op.create_index(op.f("ix_books_tenant_id"), "books", ["tenant_id"], unique=False)
    op.create_index(
        "ix_books_tenant_title", "books", ["tenant_id", "title"], unique=False
    )
    op.create_index(op.f("ix_books_title"), "books", ["title"], unique=False)
    op.create_table(
        "borrowers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("student_id", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "student_id", name="uq_borrowers_tenant_student_id"
        ),
    )
    op.create_index(op.f("ix_borrowers_email"), "borrowers", ["email"], unique=False)
    op.create_index(op.f("ix_borrowers_status"), "borrowers", ["status"], unique=False)
    op.create_index(
        op.f("ix_borrowers_tenant_id"), "borrowers", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_borrowers_tenant_name",
        "borrowers",
        ["tenant_id", "last_name", "first_name"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("hashed_password", sa.Text(), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_email_verified", sa.Boolean(), nullable=False),
        sa.Column("avatar_url", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index("ix_users_role", "users", ["role"], unique=False)
    op.create_index("ix_users_tenant_id", "users", ["tenant_id"], unique=False)
    op.create_table(
        "book_copies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("book_id", sa.UUID(), nullable=False),
        sa.Column("barcode", sa.String(length=100), nullable=False),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["book_id"], ["books.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "barcode", name="uq_book_copies_tenant_barcode"
        ),
    )
    op.create_index(
        op.f("ix_book_copies_book_id"), "book_copies", ["book_id"], unique=False
    )
    op.create_index(
        op.f("ix_book_copies_status"), "book_copies", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_book_copies_tenant_id"), "book_copies", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_book_copies_tenant_status",
        "book_copies",
        ["tenant_id", "status"],
        unique=False,
    )
    op.create_table(
        "loans",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("borrower_id", sa.UUID(), nullable=False),
        sa.Column("book_copy_id", sa.UUID(), nullable=False),
        sa.Column("issued_by_user_id", sa.UUID(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("returned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_copy_id"], ["book_copies.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["borrower_id"], ["borrowers.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["issued_by_user_id"], ["users.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_loans_book_copy_id"), "loans", ["book_copy_id"], unique=False
    )
    op.create_index(
        op.f("ix_loans_borrower_id"), "loans", ["borrower_id"], unique=False
    )
    op.create_index(op.f("ix_loans_due_date"), "loans", ["due_date"], unique=False)
    op.create_index(op.f("ix_loans_status"), "loans", ["status"], unique=False)
    op.create_index(
        "ix_loans_tenant_due_date", "loans", ["tenant_id", "due_date"], unique=False
    )
    op.create_index(op.f("ix_loans_tenant_id"), "loans", ["tenant_id"], unique=False)
    op.create_index(
        "ix_loans_tenant_status", "loans", ["tenant_id", "status"], unique=False
    )
    op.create_table(
        "fines",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("borrower_id", sa.UUID(), nullable=False),
        sa.Column("loan_id", sa.UUID(), nullable=True),
        sa.Column("reason", sa.String(length=100), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("paid_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("waived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["borrower_id"], ["borrowers.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["loan_id"], ["loans.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_fines_borrower_id"), "fines", ["borrower_id"], unique=False
    )
    op.create_index(op.f("ix_fines_loan_id"), "fines", ["loan_id"], unique=False)
    op.create_index(op.f("ix_fines_status"), "fines", ["status"], unique=False)
    op.create_index(op.f("ix_fines_tenant_id"), "fines", ["tenant_id"], unique=False)
    op.create_index(
        "ix_fines_tenant_status", "fines", ["tenant_id", "status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_fines_tenant_status", table_name="fines")
    op.drop_index(op.f("ix_fines_tenant_id"), table_name="fines")
    op.drop_index(op.f("ix_fines_status"), table_name="fines")
    op.drop_index(op.f("ix_fines_loan_id"), table_name="fines")
    op.drop_index(op.f("ix_fines_borrower_id"), table_name="fines")
    op.drop_table("fines")
    op.drop_index("ix_loans_tenant_status", table_name="loans")
    op.drop_index(op.f("ix_loans_tenant_id"), table_name="loans")
    op.drop_index("ix_loans_tenant_due_date", table_name="loans")
    op.drop_index(op.f("ix_loans_status"), table_name="loans")
    op.drop_index(op.f("ix_loans_due_date"), table_name="loans")
    op.drop_index(op.f("ix_loans_borrower_id"), table_name="loans")
    op.drop_index(op.f("ix_loans_book_copy_id"), table_name="loans")
    op.drop_table("loans")
    op.drop_index("ix_book_copies_tenant_status", table_name="book_copies")
    op.drop_index(op.f("ix_book_copies_tenant_id"), table_name="book_copies")
    op.drop_index(op.f("ix_book_copies_status"), table_name="book_copies")
    op.drop_index(op.f("ix_book_copies_book_id"), table_name="book_copies")
    op.drop_table("book_copies")
    op.drop_index("ix_users_tenant_id", table_name="users")
    op.drop_index("ix_users_role", table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index("ix_borrowers_tenant_name", table_name="borrowers")
    op.drop_index(op.f("ix_borrowers_tenant_id"), table_name="borrowers")
    op.drop_index(op.f("ix_borrowers_status"), table_name="borrowers")
    op.drop_index(op.f("ix_borrowers_email"), table_name="borrowers")
    op.drop_table("borrowers")
    op.drop_index(op.f("ix_books_title"), table_name="books")
    op.drop_index("ix_books_tenant_title", table_name="books")
    op.drop_index(op.f("ix_books_tenant_id"), table_name="books")
    op.drop_index("ix_books_tenant_author", table_name="books")
    op.drop_index(op.f("ix_books_category"), table_name="books")
    op.drop_index(op.f("ix_books_author"), table_name="books")
    op.drop_table("books")
    op.drop_index(op.f("ix_tenants_slug"), table_name="tenants")
    op.drop_table("tenants")
    # ### end Alembic commands ###
