"""settings_expansion

Revision ID: 56fe28c790d8
Revises: c5cda7d7824a
Create Date: 2026-07-11 16:02:05.080593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56fe28c790d8'
down_revision: Union[str, Sequence[str], None] = 'c5cda7d7824a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('display_name', sa.String(length=150), nullable=True))
    op.add_column('users', sa.Column('timezone', sa.String(length=60), server_default='UTC', nullable=False))
    op.add_column('users', sa.Column('theme', sa.String(length=20), server_default='system', nullable=False))
    op.add_column('users', sa.Column('notification_prefs', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notification_prefs')
    op.drop_column('users', 'theme')
    op.drop_column('users', 'timezone')
    op.drop_column('users', 'display_name')
    # ### end Alembic commands ###
