"""add_ebook_content_column

Revision ID: c5cda7d7824a
Revises: c8d26fe62c63
Create Date: 2026-07-05 17:50:57.169076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5cda7d7824a'
down_revision: Union[str, Sequence[str], None] = 'c8d26fe62c63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ebooks', sa.Column('content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ebooks', 'content')
    # ### end Alembic commands ###
